package com.liangjing.hemodialysisproject.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liangjing.hemodialysisproject.entity.PatientSchemeEntity;
import com.liangjing.hemodialysisproject.entity.UserEntity;
import com.liangjing.hemodialysisproject.entity.DoctorEntity;

import com.liangjing.hemodialysisproject.entity.PatientSchemeEntityDao;
import com.liangjing.hemodialysisproject.entity.UserEntityDao;
import com.liangjing.hemodialysisproject.entity.DoctorEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig patientSchemeEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig doctorEntityDaoConfig;

    private final PatientSchemeEntityDao patientSchemeEntityDao;
    private final UserEntityDao userEntityDao;
    private final DoctorEntityDao doctorEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        patientSchemeEntityDaoConfig = daoConfigMap.get(PatientSchemeEntityDao.class).clone();
        patientSchemeEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        doctorEntityDaoConfig = daoConfigMap.get(DoctorEntityDao.class).clone();
        doctorEntityDaoConfig.initIdentityScope(type);

        patientSchemeEntityDao = new PatientSchemeEntityDao(patientSchemeEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        doctorEntityDao = new DoctorEntityDao(doctorEntityDaoConfig, this);

        registerDao(PatientSchemeEntity.class, patientSchemeEntityDao);
        registerDao(UserEntity.class, userEntityDao);
        registerDao(DoctorEntity.class, doctorEntityDao);
    }
    
    public void clear() {
        patientSchemeEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
        doctorEntityDaoConfig.clearIdentityScope();
    }

    public PatientSchemeEntityDao getPatientSchemeEntityDao() {
        return patientSchemeEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public DoctorEntityDao getDoctorEntityDao() {
        return doctorEntityDao;
    }

}
