package /entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liangjing.hemodialysisproject.entity.PatientSchemeEntity;
import com.liangjing.hemodialysisproject.entity.UserEntity;

import /entity.PatientSchemeEntityDao;
import /entity.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig patientSchemeEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final PatientSchemeEntityDao patientSchemeEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        patientSchemeEntityDaoConfig = daoConfigMap.get(PatientSchemeEntityDao.class).clone();
        patientSchemeEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        patientSchemeEntityDao = new PatientSchemeEntityDao(patientSchemeEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(PatientSchemeEntity.class, patientSchemeEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        patientSchemeEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public PatientSchemeEntityDao getPatientSchemeEntityDao() {
        return patientSchemeEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
